### ISSUE TITLE
Lista de Tareas para 1.0 (Launch)

### ISSUE THREAD

**Issue by MinusFour** [elhacker-net/web-nuevo#21]
Lista de tareas necesarias para poner el sitio en producción. Todos estos issues necesitan revisión.

- [ ] Dar por terminado el Layout (Ver #22)
- [ ] Establecer esquema de color inicial (Ver #20) 
- [ ] Servidor para montar el frontend (Ver #19)
- [ ] Estrategia para paginas (Ver #24)
- [ ] Comunicación con el backend (Ver #23)

Tareas relacionadas con el proyecto frontend:

- [ ] API Backend
- [ ] Integración con otros servicios (blog montado en otros
